services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: producto_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:
